import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WalletAndSessionProvider from "@/components/walletProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`bg-primary text-secondary dark ${inter.className}`}>
      <WalletAndSessionProvider>{children}</WalletAndSessionProvider>
      </body>
    </html>
  );
}
