[package]
name = "sol-exchan"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "sol_exchan"


[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.30.0"
# spl-token = "3.0.0"
serde_json = "1.0"
# reqwest = { version = "0.11", features = ["json"] }
solana-client = "1.17.0"
solana-sdk = "1.17.0"  
anyhow = { version = "1.0" }
borsh = "0.9.0"

# tokio = { version = "1", features = ["full"] }
